export type BrandCampaignStatus = "live" | "planning" | "completed" | "archived" | "paused"
export type BrandCampaign = { id: string; name: string; status: BrandCampaignStatus; objective: string; category: string; startDate: string; endDate: string; brief: string; creatorIds: string[]; deliverables: { id: string; name: string; creator: string; status: "pending" | "approved" | "changes_requested" }[]; nextMilestone: string; budgetId: string; activity: { id: string; label: string; time: string }[] }
export type BrandCampaignDraft = Omit<BrandCampaign, "id" | "activity" | "deliverables" | "status" | "nextMilestone" | "budgetId"> & { deliverableNames: string[]; totalBudget: number; committed: number }

export const brandCampaignSeed: BrandCampaign[] = [
  { id: "camp_1", name: "Summer Collection Launch", status: "live", objective: "Build awareness for the summer collection through creator-led short-form content.", category: "Lifestyle", startDate: "2026-07-08", endDate: "2026-08-04", brief: "Show the collection in real summer routines with a clear product reveal in the first three seconds.", creatorIds: ["creator_1", "creator_2", "creator_3"], deliverables: [{ id: "d1", name: "Instagram Reel", creator: "Alex Rivera", status: "approved" }, { id: "d2", name: "TikTok video", creator: "Sam Jenkins", status: "pending" }, { id: "d3", name: "Instagram Stories", creator: "Mia Patel", status: "changes_requested" }], nextMilestone: "Review Sam’s final video", budgetId: "camp_1", activity: [{ id: "a1", label: "Alex’s reel approved", time: "Today" }, { id: "a2", label: "Sam submitted a final video", time: "Today" }] },
  { id: "camp_2", name: "Q3 Tech Review Series", status: "live", objective: "Earn consideration through detailed creator reviews and product demonstrations.", category: "Technology", startDate: "2026-07-15", endDate: "2026-09-15", brief: "Creators should demonstrate real use cases, feature comparisons, and an honest final verdict.", creatorIds: ["creator_2", "creator_4"], deliverables: [{ id: "d4", name: "YouTube review", creator: "Sam Jenkins", status: "pending" }, { id: "d5", name: "YouTube Short", creator: "Jordan Lee", status: "approved" }], nextMilestone: "Approve Sam’s concept", budgetId: "camp_2", activity: [{ id: "a3", label: "Jordan’s Short approved", time: "Yesterday" }] },
  { id: "camp_3", name: "Holiday Special", status: "planning", objective: "Prepare a holiday gifting campaign for creator launch in November.", category: "Seasonal", startDate: "2026-11-01", endDate: "2026-12-24", brief: "Show thoughtful gifting moments with warm, celebratory storytelling.", creatorIds: ["creator_1", "creator_3"], deliverables: [], nextMilestone: "Finalize creator shortlist", budgetId: "camp_3", activity: [{ id: "a4", label: "Campaign draft created", time: "Jul 20" }] },
]
